<?php

namespace AppBundle\Repository;

/**
 * CompsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompsRepository extends \Doctrine\ORM\EntityRepository
{
}
