<?php

namespace AppBundle\Repository;

/**
 * SetterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetterRepository extends \Doctrine\ORM\EntityRepository
{
}
